"""
Full Data Audit for the Football Database.
Produces docs/DATA_REPORT.md with all analysis required by Section 0.1.
"""
import pandas as pd
import os
import json
from collections import Counter, defaultdict

DB_PATH = r"c:\Users\Ayaan\Downloads\Video\Football\Football_Database_Expanded.xlsx"
OUT_DIR = r"c:\Users\Ayaan\Downloads\Video\Football\docs"
os.makedirs(OUT_DIR, exist_ok=True)

# ─── Load all sheets ───────────────────────────────────────────────
print("Loading workbook...")
sheets = {}
xls = pd.ExcelFile(DB_PATH)
for name in xls.sheet_names:
    sheets[name] = pd.read_excel(xls, sheet_name=name)
    print(f"  Loaded '{name}': {sheets[name].shape}")

# The master player sheet
master = sheets['All Players Master'].copy()
teams_cat = sheets['Teams & Squads Catalog'].copy()

# Also load sub-sheets for cross-reference
prem = sheets['Premier League Players']
euro = sheets['European League Players']
nations = sheets['Nations Cup Players']
fc25 = sheets['EA FC 25 Players']
fc26 = sheets['EA FC 26 Players']
fc27 = sheets['EA FC 27 Players']

lines = []
def emit(s=""):
    lines.append(s)

# ═══════════════════════════════════════════════════════════════════
# 1. SCHEMA DUMP
# ═══════════════════════════════════════════════════════════════════
emit("# DATA REPORT — Football Database Expanded")
emit()
emit(f"*Generated by `tool/audit.py`*")
emit()
emit("---")
emit()
emit("## 1. Schema Dump")
emit()

for sheet_name, df in sheets.items():
    if sheet_name == 'Overview & Data Dictionary':
        continue
    emit(f"### Sheet: `{sheet_name}`")
    emit(f"- **Rows:** {len(df)}")
    emit(f"- **Columns:** {len(df.columns)}")
    emit()
    emit("| # | Field | Inferred Type | Sample Values |")
    emit("|---|---|---|---|")
    for ci, col in enumerate(df.columns):
        dtype = str(df[col].dtype)
        samples = df[col].dropna().head(5).tolist()
        samples_str = ", ".join(str(s)[:50] for s in samples)
        emit(f"| {ci} | `{col}` | {dtype} | {samples_str} |")
    emit()

# ═══════════════════════════════════════════════════════════════════
# 2. ROW COUNTS
# ═══════════════════════════════════════════════════════════════════
emit("## 2. Row Counts")
emit()

total_players = len(master)
unique_player_ids = master['Player ID'].nunique()
unique_player_names = master['Player Name'].nunique()
unique_clubs = master['Team Code'].nunique()
unique_club_names = master['Team Name'].nunique()
unique_leagues = master['Mode'].nunique()
modes = master['Mode'].unique().tolist()
unique_seasons = master['Season / Year'].nunique()
season_range = f"{master['Season / Year'].min()} – {master['Season / Year'].max()}"

# Nations: from the Nations Cup sheet, team names are nations
nations_teams = nations['Team Name'].unique()
unique_nations = len(nations_teams)

emit(f"| Metric | Count |")
emit(f"|---|---|")
emit(f"| Total player-roster instances (All Players Master) | {total_players:,} |")
emit(f"| Unique Player IDs | {unique_player_ids:,} |")
emit(f"| Unique Player Names | {unique_player_names:,} |")
emit(f"| Unique Club/Team Codes | {unique_clubs:,} |")
emit(f"| Unique Club/Team Names | {unique_club_names:,} |")
emit(f"| Modes (Leagues) | {unique_leagues} ({', '.join(modes)}) |")
emit(f"| National Teams (Nations Cup) | {unique_nations} |")
emit(f"| Unique Seasons/Years | {unique_seasons} ({season_range}) |")
emit(f"| Team & Squads Catalog entries | {len(teams_cat):,} |")
emit()

# Sub-sheet counts
emit("### Per-sheet breakdown")
emit()
emit("| Sheet | Rows |")
emit("|---|---|")
for name, df in sheets.items():
    if name != 'Overview & Data Dictionary':
        emit(f"| {name} | {len(df):,} |")
emit()

# ═══════════════════════════════════════════════════════════════════
# 3. COVERAGE TABLE
# ═══════════════════════════════════════════════════════════════════
emit("## 3. Coverage Table (All Players Master)")
emit()
emit("| Field | % Non-Null | % Empty String | Distinct | Min | Max |")
emit("|---|---|---|---|---|---|")

for col in master.columns:
    total = len(master)
    non_null = master[col].notna().sum()
    pct_non_null = round(100 * non_null / total, 1)
    
    # Empty string check
    if master[col].dtype == object:
        empty_str = (master[col] == '').sum()
        pct_empty = round(100 * empty_str / total, 1)
    else:
        pct_empty = 0.0
    
    distinct = master[col].nunique()
    
    # Min/max for numerics
    if pd.api.types.is_numeric_dtype(master[col]):
        col_min = master[col].min()
        col_max = master[col].max()
    else:
        col_min = "—"
        col_max = "—"
    
    emit(f"| `{col}` | {pct_non_null}% | {pct_empty}% | {distinct:,} | {col_min} | {col_max} |")

emit()

# ═══════════════════════════════════════════════════════════════════
# 4. DISTRIBUTION CHECKS
# ═══════════════════════════════════════════════════════════════════
emit("## 4. Distribution Checks")
emit()

# 4a. Players per mode (league)
emit("### 4.1 Players per Mode")
emit()
mode_counts = master['Mode'].value_counts()
emit("| Mode | Player Instances |")
emit("|---|---|")
for mode, cnt in mode_counts.items():
    emit(f"| {mode} | {cnt:,} |")
emit()

# 4b. Players per club (top 30)
emit("### 4.2 Players per Club (top 30)")
emit()
club_counts = master.groupby(['Team Code', 'Team Name']).size().sort_values(ascending=False)
emit("| Code | Club | Instances |")
emit("|---|---|---|")
for (code, name), cnt in club_counts.head(30).items():
    emit(f"| {code} | {name} | {cnt:,} |")
emit()

# 4c. Players per nation (Nations Cup teams, top 30)
emit("### 4.3 National Teams (Nations Cup, top 20)")
emit()
nation_counts = nations.groupby('Team Name').size().sort_values(ascending=False)
emit("| Nation | Player Instances |")
emit("|---|---|")
for nation, cnt in nation_counts.head(20).items():
    emit(f"| {nation} | {cnt:,} |")
emit()

# 4d. Rating histogram
emit("### 4.4 Rating Distribution (Overall Rating, buckets of 5)")
emit()
ratings = master['Overall Rating (OVR)'].dropna().astype(int)
buckets = {}
for r in ratings:
    bucket = (r // 5) * 5
    key = f"{bucket}–{bucket+4}"
    buckets[key] = buckets.get(key, 0) + 1

emit("| Rating Range | Count |")
emit("|---|---|")
for key in sorted(buckets.keys(), key=lambda x: int(x.split('–')[0])):
    emit(f"| {key} | {buckets[key]:,} |")
emit()

# 4e. Age histogram
emit("### 4.5 Age Distribution")
emit()
ages = master['Age'].dropna().astype(int)
age_counts = ages.value_counts().sort_index()
emit("| Age | Count |")
emit("|---|---|")
for age, cnt in age_counts.items():
    emit(f"| {age} | {cnt:,} |")
emit()

# Age nulls
age_null = master['Age'].isna().sum()
emit(f"**Age missing:** {age_null:,} rows ({round(100*age_null/total_players, 1)}%)")
emit()

# 4f. Position counts
emit("### 4.6 Position Counts (Primary Position)")
emit()
pos_counts = master['Primary Position'].value_counts()
emit("| Position | Count |")
emit("|---|---|")
for pos, cnt in pos_counts.items():
    emit(f"| {pos} | {cnt:,} |")
emit()

# 4g. Season distribution
emit("### 4.7 Players per Season/Year")
emit()
season_counts = master.groupby('Season / Year').size().sort_index()
emit("| Season | Count |")
emit("|---|---|")
for season, cnt in season_counts.items():
    emit(f"| {season} | {cnt:,} |")
emit()

# ═══════════════════════════════════════════════════════════════════
# 5. RELATIONAL INTEGRITY
# ═══════════════════════════════════════════════════════════════════
emit("## 5. Relational Integrity")
emit()

# 5a. Orphaned club IDs: teams in players but not in Teams catalog
player_squads = set(master['Squad ID'].unique())
catalog_squads = set(teams_cat['Squad ID'].unique())
orphaned = player_squads - catalog_squads
missing_players = catalog_squads - player_squads

emit(f"### 5.1 Squad ID cross-reference")
emit(f"- Player sheet squad IDs: **{len(player_squads):,}**")
emit(f"- Catalog squad IDs: **{len(catalog_squads):,}**")
emit(f"- Orphaned (in players but not catalog): **{len(orphaned)}**")
if orphaned:
    emit(f"  - Examples: {list(orphaned)[:10]}")
emit(f"- Missing (in catalog but no players): **{len(missing_players)}**")
if missing_players:
    emit(f"  - Examples: {list(missing_players)[:10]}")
emit()

# 5b. Players with no league (Mode blank)
no_mode = master['Mode'].isna().sum()
emit(f"### 5.2 Players with no Mode (league): **{no_mode}**")
emit()

# 5c. Clubs with no players
teams_in_catalog = set(teams_cat['Squad ID'].unique())
teams_with_players = set(master['Squad ID'].unique())
clubs_no_players = teams_in_catalog - teams_with_players
emit(f"### 5.3 Squads in catalog with no player data: **{len(clubs_no_players)}**")
if clubs_no_players:
    emit(f"  - Examples: {list(clubs_no_players)[:10]}")
emit()

# 5d. Duplicate player names
name_counts = master.groupby('Player Name').size()
dup_names = name_counts[name_counts > 1]
# But many duplicates are legitimate (same player across seasons)
# Check for duplicate Player ID + Season
id_season_dup = master.duplicated(subset=['Player ID', 'Season / Year', 'Mode'], keep=False)
id_season_dup_count = id_season_dup.sum()
emit(f"### 5.4 Duplicate Detection")
emit(f"- Players with the same name appearing multiple times: **{len(dup_names):,}** (expected — same player across seasons)")
emit(f"- Exact duplicates (same Player ID + Season + Mode): **{id_season_dup_count}**")
if id_season_dup_count > 0:
    dups = master[id_season_dup].head(10)[['Player ID', 'Player Name', 'Season / Year', 'Mode', 'Team Name']]
    emit(f"  - Sample duplicates:")
    emit(f"```")
    emit(dups.to_string())
    emit(f"```")
emit()

# 5e. Duplicate Player IDs across different players (same ID, different names)
id_name_map = master.groupby('Player ID')['Player Name'].nunique()
multi_name_ids = id_name_map[id_name_map > 1]
emit(f"### 5.5 Player ID consistency")
emit(f"- Player IDs mapping to multiple distinct names: **{len(multi_name_ids)}**")
if len(multi_name_ids) > 0:
    emit("  - Samples:")
    for pid in list(multi_name_ids.index)[:10]:
        names = master[master['Player ID'] == pid]['Player Name'].unique().tolist()
        emit(f"    - ID `{pid}`: {names}")
emit()

# ═══════════════════════════════════════════════════════════════════
# 6. CAREER-HISTORY DEPTH
# ═══════════════════════════════════════════════════════════════════
emit("## 6. Career-History Depth")
emit()
emit("This section assesses whether the database contains various career-related data fields.")
emit()

# Previous clubs: can we determine if a player played for multiple clubs?
player_clubs = master.groupby('Player ID')['Team Code'].apply(lambda x: set(x))
multi_club_players = sum(1 for clubs in player_clubs if len(clubs) > 1)
total_unique_players = len(player_clubs)
pct_multi_club = round(100 * multi_club_players / total_unique_players, 1)

# Per-season stats: does the DB have per-season stats (goals, assists, appearances)?
has_goals = 'Goals' in master.columns or 'Career Goals' in master.columns
has_assists = 'Assists' in master.columns or 'Career Assists' in master.columns
has_appearances = 'Appearances' in master.columns or 'Career Appearances' in master.columns

# Trophies
has_trophies = any('trophy' in c.lower() or 'title' in c.lower() or 'winner' in c.lower() for c in master.columns)

# International caps
has_caps = any('cap' in c.lower() or 'international' in c.lower() for c in master.columns)

# Transfer values
has_value = any('value' in c.lower() or 'market' in c.lower() or 'transfer' in c.lower() for c in master.columns)

# Preferred foot
has_foot = any('foot' in c.lower() or 'preferred' in c.lower() for c in master.columns)

# Height
has_height = any('height' in c.lower() or 'tall' in c.lower() for c in master.columns)

# Weight
has_weight = any('weight' in c.lower() for c in master.columns)

# Nationality
has_nationality = any('nation' in c.lower() or 'country' in c.lower() for c in master.columns)

# Player seasons (multiple entries per player across years)
player_seasons = master.groupby('Player ID')['Season / Year'].nunique()
multi_season = sum(1 for s in player_seasons if s > 1)
pct_multi_season = round(100 * multi_season / total_unique_players, 1)

items = [
    ("Previous clubs per player", f"PARTIAL ({pct_multi_club}%)", 
     f"Inferable: {multi_club_players:,} of {total_unique_players:,} unique player IDs appear at 2+ clubs across seasons. No explicit 'transfer history' field."),
    ("Per-season stats (goals/assists/apps)", "NO",
     "No goals, assists, or appearances columns exist. Only attribute ratings (PAC/SHO/PAS/DRI/DEF/PHY) and OVR."),
    ("Trophies", "NO", "No trophy/title/winner fields."),
    ("International caps", "NO", "No caps or international appearance fields."),
    ("Career goals/assists totals", "NO", "No career goal or assist totals."),
    ("Transfer values", "NO", "No market value or transfer fee fields."),
    ("Preferred foot", "NO", "No preferred foot field."),
    ("Height", "NO", "No height field."),
    ("Weight", "NO", "No weight field."),
    ("Nationality", "PARTIAL", 
     f"Not a direct field. Can be inferred from Nations Cup team membership ({unique_nations} nations). Club-mode players have no nationality column."),
    ("Multi-season presence", f"PARTIAL ({pct_multi_season}%)",
     f"{multi_season:,} players appear across multiple seasons, providing a temporal dimension."),
    ("Attribute ratings (6 stats)", "YES (100%)",
     "All players have PAC/SHO/PAS/DRI/DEF/PHY. GK stats use the same columns with different semantics."),
    ("Jersey colours (per team)", "YES",
     f"Teams & Squads Catalog has Primary/Secondary Jersey Color for {teams_cat['Primary Jersey Color'].notna().sum()}/{len(teams_cat)} teams."),
]

emit("| Data Element | Verdict | Notes |")
emit("|---|---|---|")
for name, verdict, notes in items:
    emit(f"| {name} | **{verdict}** | {notes} |")
emit()

# ═══════════════════════════════════════════════════════════════════
# 7. RED FLAGS
# ═══════════════════════════════════════════════════════════════════
emit("## 7. Red Flags")
emit()

# 7a. Rating 0 or extreme
extreme_ratings = master[(master['Overall Rating (OVR)'] < 40) | (master['Overall Rating (OVR)'] > 99)]
emit(f"### 7.1 Extreme ratings (OVR < 40 or > 99): **{len(extreme_ratings)}**")
if len(extreme_ratings) > 0:
    emit("| Player | OVR | Team | Season |")
    emit("|---|---|---|---|")
    for _, row in extreme_ratings.head(10).iterrows():
        emit(f"| {row['Player Name']} | {row['Overall Rating (OVR)']} | {row['Team Name']} | {row['Season / Year']} |")
emit()

# 7b. Age 0 or extreme
if master['Age'].notna().any():
    extreme_ages = master[(master['Age'].notna()) & ((master['Age'] < 15) | (master['Age'] > 45))]
    emit(f"### 7.2 Extreme ages (< 15 or > 45): **{len(extreme_ages)}**")
    if len(extreme_ages) > 0:
        emit("| Player | Age | Team | Season |")
        emit("|---|---|---|---|")
        for _, row in extreme_ages.head(10).iterrows():
            emit(f"| {row['Player Name']} | {row['Age']} | {row['Team Name']} | {row['Season / Year']} |")
emit()

# 7c. Mojibake / encoding issues
import re
mojibake_pattern = re.compile(r'[�ï¿½]|\\x[0-9a-f]{2}')
mojibake_names = master[master['Player Name'].astype(str).str.contains(r'�', na=False)]
emit(f"### 7.3 Encoding issues (replacement char '�' in names): **{len(mojibake_names)}**")
if len(mojibake_names) > 0:
    sample_names = mojibake_names['Player Name'].unique()[:20]
    emit("Sample names with encoding issues:")
    for n in sample_names:
        emit(f"  - `{n}`")
emit()

# 7d. Missing shirt numbers
shirt_null = master['Shirt Number'].isna().sum()
emit(f"### 7.4 Missing shirt numbers: **{shirt_null:,}** ({round(100*shirt_null/total_players, 1)}%)")
emit()

# 7e. Attribute stats of 0 or very low
for stat_col in ['Pace / Diving (PAC)', 'Shooting / Handling (SHO)', 'Passing / Kicking (PAS)', 
                  'Dribbling / Reflexes (DRI)', 'Defending / Speed (DEF)', 'Physicality / Positioning (PHY)']:
    zero_stats = master[master[stat_col] < 10]
    if len(zero_stats) > 0:
        emit(f"### 7.x `{stat_col}` values < 10: **{len(zero_stats)}**")

# 7f. Placeholder-looking data
emit(f"### 7.5 Squad Rating Weight coverage")
weight_null = master['Squad Rating Weight'].isna().sum()
emit(f"- Missing: **{weight_null:,}** ({round(100*weight_null/total_players, 1)}%)")
emit()

# 7g. Data Source distribution
emit(f"### 7.6 Data Source distribution")
emit()
source_counts = master['Data Source / ID Type'].value_counts()
emit("| Source | Count |")
emit("|---|---|")
for src, cnt in source_counts.items():
    emit(f"| {src} | {cnt:,} |")
emit()

# 7h. Player ID types
emit(f"### 7.7 Player ID types")
emit()
numeric_ids = master['Player ID'].apply(lambda x: str(x).isdigit()).sum()
retro_ids = master['Player ID'].astype(str).str.startswith('900000').sum()
wc_ids = master['Player ID'].astype(str).str.startswith('P-').sum()
emit(f"- Numeric (EA FIFA IDs): **{numeric_ids:,}**")
emit(f"  - Of which retro synthetic (9000xxx): **{retro_ids:,}**")
emit(f"- World Cup IDs (P-xxxxx): **{wc_ids:,}**")
emit(f"- Other: **{total_players - numeric_ids - wc_ids:,}**")
emit()

# ═══════════════════════════════════════════════════════════════════
# ADDITIONAL: Cross-mode player tracking
# ═══════════════════════════════════════════════════════════════════
emit("## 8. Cross-Mode Player Tracking (Bonus Analysis)")
emit()

# Can we match players across Premier League, European League, and Nations Cup?
# PL/Euro use numeric FIFA IDs, Nations Cup uses P-xxxxx
# Check if any FIFA IDs appear in both PL and Euro
pl_ids = set(prem['Player ID'].unique())
euro_ids = set(euro['Player ID'].unique())
nc_ids = set(nations['Player ID'].unique())

pl_euro_overlap = pl_ids & euro_ids
emit(f"- Premier League ↔ European League shared Player IDs: **{len(pl_euro_overlap):,}**")
emit(f"- Premier League ↔ Nations Cup shared Player IDs: **{len(pl_ids & nc_ids):,}**")
emit(f"- European League ↔ Nations Cup shared Player IDs: **{len(euro_ids & nc_ids):,}**")
emit()
emit("*Nations Cup uses a different ID scheme (P-xxxxx) so cross-referencing requires name matching, not ID matching.*")
emit()

# Check for name-based overlap between club modes and Nations Cup
pl_names = set(prem['Player Name'].str.lower().unique())
euro_names = set(euro['Player Name'].str.lower().unique())
nc_names = set(nations['Player Name'].str.lower().unique())

pl_nc_name_overlap = pl_names & nc_names
euro_nc_name_overlap = euro_names & nc_names
emit(f"- PL ↔ Nations Cup name overlap: **{len(pl_nc_name_overlap):,}**")
emit(f"- Euro ↔ Nations Cup name overlap: **{len(euro_nc_name_overlap):,}**")
emit()

# ═══════════════════════════════════════════════════════════════════
# ADDITIONAL: Unique players with nationality derivation
# ═══════════════════════════════════════════════════════════════════
emit("## 9. Nationality Derivation Potential")
emit()

# From Nations Cup, we can derive nationality for players
# Count distinct nations
nc_nations = nations['Team Name'].unique()
emit(f"- Nations Cup covers **{len(nc_nations)}** national teams")
emit(f"- Nations: {', '.join(sorted(nc_nations))}")
emit()

# ═══════════════════════════════════════════════════════════════════
# ADDITIONAL: League structure
# ═══════════════════════════════════════════════════════════════════
emit("## 10. League & Competition Structure")
emit()

# What clubs are in each mode?
for mode in master['Mode'].unique():
    mode_data = master[master['Mode'] == mode]
    teams = mode_data[['Team Code', 'Team Name']].drop_duplicates()
    seasons = sorted(mode_data['Season / Year'].unique())
    emit(f"### {mode}")
    emit(f"- **Teams:** {len(teams)}")
    emit(f"- **Seasons:** {len(seasons)} ({min(seasons)}–{max(seasons)})")
    emit(f"- **Clubs:** {', '.join(teams['Team Name'].unique()[:40])}")
    if len(teams['Team Name'].unique()) > 40:
        emit(f"  - ... and {len(teams['Team Name'].unique()) - 40} more")
    emit()

# ═══════════════════════════════════════════════════════════════════
# Write output
# ═══════════════════════════════════════════════════════════════════
output = "\n".join(lines)
outpath = os.path.join(OUT_DIR, "DATA_REPORT.md")
with open(outpath, "w", encoding="utf-8") as f:
    f.write(output)

print(f"\n✅ DATA_REPORT.md written to {outpath}")
print(f"   Total lines: {len(lines)}")
